# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NavigateU' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NavigateU
    
   pod 'SnapKit', '~> 5.7.1'
   pod 'SwiftLint', '~> 0.54.0'


end
