# Uncomment the next line to define a global platform for your project
platform :ios, '17.22'

target 'NavigateU' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NavigateU
    
    pod 'SnapKit', '~> 5.7.1'
    pod 'SwiftLint', '~> 0.54.0'

   # for Mac M1
#   post_install do |installer_representation|
#       installer_representation.pods_project.targets.each do |target|
#           target.build_configurations.each do |config|
#               config.build_settings['ONLY_ACTIVE_ARCH'] = 'NO'
#               config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
#               config.build_settings['VALID_ARCHS'] = 'arm64, arm64e, x86_64'
#           end
#       end
#    end
end
